name: movies
namespace: web-app

replicaCount: 3

image:
  repository: siddharth67/movies-ui
  pullPolicy: Always
  tag: "nginx"

service:
  type: NodePort
  port: 80  
  nodePort: 30080
  protocol: TCP
  targetPort: 80

