apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: movies
  namespace: argocd
project: apps

source:
  repoURL: git@github.com:andreelidio/k8s-lab.git
  targetRevision: HEAD
  path: charts/webapp

  helm:
    - valueFiles:
        - ../../apps/solar-system/values.yaml
destination:
  server: https://kubernetes.default.svc
  namespace: web-app
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true