replicaCount: 2

image:
  repository: siddharth67/solar-system
  tag: v9
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30333

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 50m
    memory: 128Mi

probes:
  readinessPath: /
  livenessPath: /
  initialDelaySeconds: 5
  livenessInitialDelaySeconds: 30
  periodSeconds: 10

namespace: solar-system